const user = [
  { email: 'dvesp1901@gmail.com', fullname: 'Dhruv Dve' },
  { email: 'marek10a123@gmail.com', fullname: 'Marek 10a' },
  { email: '24cttechnologies@gmail.com', fullname: 'AKASH KALOLIYA' },
  { email: 'ansarifaizan846@gmail.com', fullname: 'Faizan Ansari' },
  { email: 'deepakchouhan10000@gmail.com', fullname: 'Deepak Chouhan' },
  { email: 'hetvi.implies@gmail.com', fullname: 'Hetvi Borad' },
  { email: 'shubhamsonkar.rabs@gmail.com', fullname: 'Shubham Sonkar' },
  { email: 'karanmhetre9@gmail.com', fullname: 'Karan Mhetre' },
  { email: 'ujwalkagrawal@gmail.com', fullname: 'Ujwal Agrawal' },
  { email: 'carlos123df@gmail.com', fullname: 'Carlos Rios' },
  { email: 'abhishek.singh@byldd.com', fullname: 'Abhishek Singh' },
  { email: 'helton.wylammi@vortexz.com.br', fullname: 'Helton Wylammi' },
  { email: 'luc.nguyen@flexifyme.com', fullname: 'Luc Nguyen Thanh' },
  { email: 'abhishek.sharma@truxcargo.com', fullname: 'Abhishek Sharma' },
  { email: 'mazharmalik044@gmail.com', fullname: 'Mazhar Ali' },
  { email: 'abadumsolutions@gmail.com', fullname: 'Abadum Solutions' },
  { email: 'aditya@primafelicitas.com', fullname: 'Aditya Rajput' },
  { email: 'is0409390@gmail.com', fullname: 'Imran Shaikh' },
  { email: 'siddharthbhadoriya1@gmail.com', fullname: 'Siddharth Bhadoriya' },
  { email: 'mohit.kody@gmail.com', fullname: 'mohit Kody' },
  { email: 'bharat.bhushan.henceforth@gmail.com', fullname: 'Bharat Bhushan' },
  { email: 'leonardopasaribu8@gmail.com', fullname: 'Leonardo Pasaribu' },
  { email: 'vihan9191@gmail.com', fullname: 'vihan dave' },
  { email: 'harshil.micrasol@gmail.com', fullname: 'Harshil Thummar' },
  { email: 'chandankalita.public@gmail.com', fullname: 'Chandan Kalita' },
  { email: 'creativorajesh@gmail.com', fullname: 'Creativo Roy' },
  { email: 'akash.rebala@extwebtech.in', fullname: 'Akash Rebala' },
  { email: 'vratikasoni1419@gmail.com', fullname: 'Vratika Soni' },
  { email: 'nirav.chauhan.dev@gmail.com', fullname: 'Nirav Chauhan' },
  { email: 'walbertdavid2000@gmail.com', fullname: 'Walbert Benitez' },
  { email: 'dhruvin.coderkube@gmail.com', fullname: 'Dhruvin Munjapara' },
  { email: 'campuscommand959@gmail.com', fullname: 'Campus Command' },
  { email: 'evgeniyg1727@gmail.com', fullname: 'Evgeniy Melber' },
  { email: 'bharat@arbadev.com', fullname: 'Bharat Vishvkarma' },
];
